player : '/usr/bin/afplay' # for Mac
# player : '/usr/bin/mpg321' # for Linux

stopper : '/usr/local/bin/pkill afplay' # for Mac
# stopper : '/usr/local/bin/pkill mpg321' # for Linux

tmp_dir : '/var/tmp/audio-server'
